project_id = "kdrtvdkmggscyrkmxhws"

[functions.categorize-grocery]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.setup-stripe-products]
verify_jwt = false
