project_id = "kdrtvdkmggscyrkmxhws"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.categorize-grocery]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-portal-session]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.revenuecat-webhook]
    verify_jwt = false
  [functions.setup-stripe-products]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.send-admin-alert]
    verify_jwt = true
  [functions.send-household-invite]
    verify_jwt = true
